[template]
cargo_generate_version = ">=0.18.0"
exclude = ["cyw43-firmware"]

[placeholders.template]
prompt = "Choose a template"
choices = [
    "Blinky",
    "GPIO In/Out",
    "USB device CDC",
    "Wi-Fi HTTP Client"
]
default = "Blinky"
type = "string"

[conditional.'template != "Wi-Fi HTTP Client"']
ignore = ["cyw43-firmware", "src/private_info.rs"]
