[template]
cargo_generate_version = ">=0.18.0"
exclude = ["cyw43-firmware"]

[placeholders.template]
prompt = "Choose a template"
choices = [
    "Blinky",
    "GPIO In/Out",
    "PWM LED",
    "UART Echo",
    "USB Device CDC",
    "USB Device HID Keyboard and Mouse",
    "I2C SSD1306",
    "I2C SSD1306 + DS3231",
    "Wi-Fi Scan",
    "Wi-Fi HTTP Client"
]
default = "Blinky"
type = "string"

[conditional.'template != "PWM LED"']
ignore = ["src/pwm_util.rs"]

[conditional.'template != "Wi-Fi Scan"']
ignore = ["cyw43-firmware"]

[conditional.'template != "Wi-Fi HTTP Client"']
ignore = ["cyw43-firmware", "src/private_info.rs"]
